"""
Module 5 — Security Test Generator

Consumes a verified traceability chain:

    SecurityFinding → RemediationPlan → AppliedPatch

and produces:

    SecurityRegressionTest   — a behavioral mock-based security test
    DesiredOutcome           — the explicit security outcome the engineering
                               loop must eventually achieve

Architecture boundary
---------------------
This module MUST NOT:
  * apply patches or modify source files;
  * execute the generated test;
  * determine whether remediation succeeded;
  * implement retry / rollback / orchestration;
  * access external networks, APIs, or LLMs.

It MUST:
  * validate the finding → plan → patch traceability chain;
  * reject mismatched or non-applied artifacts immediately;
  * produce behavioral tests — not source-string assertions;
  * keep generated tests safe (no destructive payloads, no real execution);
  * be deterministic — identical inputs produce identical output.

Public interface
----------------
  generate_security_test(finding, plan, patch, inventory)
      -> tuple[SecurityRegressionTest, DesiredOutcome]

  persist_security_test(test, repo_path)
      -> Path   (the file written; explicit, separate from generation)
"""

from __future__ import annotations

import ast
import hashlib
import logging
import os
import textwrap
from pathlib import Path
from typing import Optional

from secure_swe.models import (
    AppliedPatch,
    DesiredOutcome,
    RemediationPlan,
    RepoInventory,
    SecurityFinding,
    SecurityRegressionTest,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Sentinel value
# ---------------------------------------------------------------------------

# A harmless shell-like string that contains a metacharacter sequence.
# Used as the adversarial test input for behavioral verification.
# It must never actually execute: the test mocks process invocation.
_SENTINEL_INPUT = "example.invalid; SENTINEL"

# ---------------------------------------------------------------------------
# Security invariants for the command-injection vertical slice
# ---------------------------------------------------------------------------

_SECURITY_INVARIANTS = [
    "Dynamic/untrusted input is not interpreted by a shell.",
    "Shell metacharacters in dynamic arguments remain ordinary string data.",
    "The original dangerous execution pattern (shell=True or os.system with "
    "dynamic concatenation) has been eliminated from the target file.",
]

_REGRESSION_REQUIREMENTS = [
    "All existing project tests must continue to pass after remediation.",
    "The security regression test generated by this module must pass.",
]

_VERIFICATION_REQUIREMENTS = [
    "The original finding must no longer be reproducible or detectable by "
    "static analysis of the patched file.",
    "The remediation must correspond to the original finding (traceability "
    "chain finding → plan → patch must be intact).",
    "An independent verifier must confirm that no new security findings of "
    "equal or higher severity were introduced by the patch.",
    "The patched implementation must pass all behavioral security assertions "
    "in the generated SecurityRegressionTest.",
]

# ---------------------------------------------------------------------------
# Supported vulnerability types
# ---------------------------------------------------------------------------

_SUPPORTED_VULNERABILITY_TYPES = frozenset(["command_injection"])

# ---------------------------------------------------------------------------
# ID derivation
# ---------------------------------------------------------------------------


def _test_id(patch_id: str) -> str:
    """Deterministic 16-char hex test identifier derived from the patch ID."""
    raw = f"sectest|{patch_id}"
    return hashlib.sha256(raw.encode()).hexdigest()[:16]


def _outcome_id(finding_id: str) -> str:
    """Deterministic 16-char hex outcome identifier derived from the finding ID."""
    raw = f"outcome|{finding_id}"
    return hashlib.sha256(raw.encode()).hexdigest()[:16]


# ---------------------------------------------------------------------------
# Traceability validation
# ---------------------------------------------------------------------------


class TraceabilityError(ValueError):
    """
    Raised when the finding → plan → patch chain is inconsistent.

    This is a hard failure: test generation must be rejected rather than
    producing a test whose traceability is questionable.
    """


class GenerationError(ValueError):
    """
    Raised when a safe behavioral test cannot be constructed for other reasons
    (unsupported vulnerability type, missing source evidence, etc.).
    """


def _validate_chain(
    finding: SecurityFinding,
    plan: RemediationPlan,
    patch: AppliedPatch,
) -> None:
    """
    Enforce full traceability consistency.

    Rules verified (all must hold):
      1. plan.finding_id == finding.id
      2. patch.plan_id   == plan.plan_id
      3. patch.finding_id == finding.id
      4. patch.applied   is True

    Raises TraceabilityError with an explanation on any violation.
    """
    if plan.finding_id != finding.id:
        raise TraceabilityError(
            f"Plan finding_id '{plan.finding_id}' does not match "
            f"finding id '{finding.id}'.  "
            f"The plan was not derived from this finding."
        )

    if patch.plan_id != plan.plan_id:
        raise TraceabilityError(
            f"Patch plan_id '{patch.plan_id}' does not match "
            f"plan plan_id '{plan.plan_id}'.  "
            f"The patch was not produced by this plan."
        )

    if patch.finding_id != finding.id:
        raise TraceabilityError(
            f"Patch finding_id '{patch.finding_id}' does not match "
            f"finding id '{finding.id}'.  "
            f"The patch traceability chain is broken."
        )

    if not patch.applied:
        raise TraceabilityError(
            f"Patch '{patch.patch_id}' has applied=False "
            f"(status: {patch.status!r}).  "
            f"Cannot generate a security regression test for a patch that was "
            f"not successfully applied."
        )


# ---------------------------------------------------------------------------
# Source inspection helpers
# ---------------------------------------------------------------------------


def _get_source(inventory: RepoInventory, relative_path: str) -> Optional[str]:
    """Return source content for *relative_path* from the inventory, or None."""
    for entry in inventory.files:
        if entry.relative_path == relative_path:
            return entry.content
    return None


def _infer_module_path(relative_path: str) -> str:
    """
    Convert a repository-relative file path to a Python dotted module path.

    e.g. "app/system.py" → "app.system"
         "vuln.py"        → "vuln"
    """
    # Normalise separators to forward-slash, strip .py suffix.
    path = relative_path.replace("\\", "/")
    if path.endswith(".py"):
        path = path[:-3]
    return path.replace("/", ".")


def _infer_function_name(source: str, target_line: int) -> Optional[str]:
    """
    Return the name of the function defined at or enclosing *target_line*.

    Parses the source AST and returns the innermost function whose body
    contains *target_line*.  Returns None if the call cannot be mapped to a
    function.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return None

    best: Optional[str] = None
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        # Check if the target line falls within this function's body.
        start = node.lineno
        end = node.end_lineno if hasattr(node, "end_lineno") else node.lineno
        if start <= target_line <= end:
            best = node.name  # innermost wins; keep overwriting
    return best


def _detect_call_pattern(source: str, target_line: int) -> Optional[str]:
    """
    Return the sink call as a short label for code generation hints.

    Returns e.g. "subprocess.run", "os.system", or None.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return None

    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and node.lineno == target_line:
            try:
                return ast.unparse(node.func)
            except Exception:  # pragma: no cover
                pass
    return None


# ---------------------------------------------------------------------------
# Test-code builders
# ---------------------------------------------------------------------------


def _build_subprocess_list_test(
    module_path: str,
    function_name: str,
    test_name: str,
    sentinel: str,
    sink: str,
) -> str:
    """
    Build a behavioral security regression test for a remediation that replaced
    a shell-string invocation with a subprocess argument list.

    The test:
      1. Imports the function under test.
      2. Patches the subprocess/os call so no real process runs.
      3. Calls the function with *sentinel* (a shell-metacharacter-containing
         string) as the dynamic argument.
      4. Asserts that the mock was called with the sentinel as a discrete list
         element — never as an interpolated shell string.
      5. Verifies the mock was called exactly once (no unexpected re-invocation).

    The sentinel never actually executes; the mock intercepts the call.
    """
    # Determine the mock target based on the original sink.
    if sink == "os.system":
        # The remediation replaces os.system with subprocess.run, so the
        # regression test must observe the post-remediation execution boundary.
        mock_target = "subprocess.run"
        mock_import = "import subprocess"
        arg_assertion = f'    mock_exec.assert_called_once()\n'
        arg_assertion += (
            f'    call_args = mock_exec.call_args\n'
            f'    # The first positional argument must be a list, not a string.\n'
            f'    first_arg = call_args[0][0]\n'
            f'    assert isinstance(first_arg, list), (\n'
            f'        f"Expected argument list, got {{type(first_arg).__name__!r}}"\n'
            f'    )\n'
            f'    # The sentinel must appear as a standalone list element.\n'
            f'    assert {repr(sentinel)} in first_arg, (\n'
            f'        "Sentinel input was not preserved as a discrete list element."\n'
            f'    )\n'
            f'    # No shell string containing the sentinel should be present.\n'
            f'    for arg in call_args[0]:\n'
            f'        if isinstance(arg, str) and ";" in arg and len(arg) > len({repr(sentinel)}):\n'
            f'            raise AssertionError(\n'
            f'                f"Shell-metacharacter string found in call: {{arg!r}}"\n'
            f'            )\n'
        )
    else:
        # subprocess.run / subprocess.call / subprocess.Popen
        mock_target = "subprocess.run"
        mock_import = "import subprocess"
        arg_assertion = (
            f'    call_args = mock_exec.call_args\n'
            f'    # The first positional argument must be a list, not a string.\n'
            f'    first_arg = call_args[0][0]\n'
            f'    assert isinstance(first_arg, list), (\n'
            f'        f"Expected argument list, got {{type(first_arg).__name__!r}}"\n'
            f'    )\n'
            f'    # The sentinel must appear as a standalone list element.\n'
            f'    assert {repr(sentinel)} in first_arg, (\n'
            f'        "Sentinel input was not preserved as a discrete list element."\n'
            f'    )\n'
            f'    # Confirm shell=True is NOT passed (no shell expansion).\n'
            f'    kwargs = call_args[1] if len(call_args) > 1 else {{}}\n'
            f'    assert kwargs.get("shell", False) is not True, (\n'
            f'        "shell=True must not be present in the remediated call."\n'
            f'    )\n'
            f'    # The sentinel was called exactly once (no unexpected retries).\n'
            f'    mock_exec.assert_called_once()\n'
        )

    code = f'''\
"""
Security regression test for command-injection finding.

Generated by secure_swe.test_generator.
DO NOT edit manually — regenerate from the original finding chain.

Security property
-----------------
Dynamic/untrusted input must not be interpreted as shell syntax.
Shell metacharacters must remain ordinary argument data.

Sentinel input used: {repr(sentinel)}
The sentinel is never executed — subprocess/os calls are mocked.
"""
from __future__ import annotations

{mock_import}
from unittest.mock import patch, MagicMock

from {module_path} import {function_name}


def {test_name}() -> None:
    """
    Behavioral security regression test.

    Verifies that passing a value containing shell metacharacters
    ({repr(sentinel)}) to {function_name}() does NOT result in
    shell interpretation of those characters.

    Strategy
    --------
    * Mock all subprocess / os.system execution so no real process runs.
    * Call the function under test with the adversarial sentinel input.
    * Assert that the mock received the sentinel as a discrete list element.
    * Assert that shell=True is absent from the call (for subprocess sinks).

    This test does NOT:
    * delete files;
    * modify system state;
    * execute destructive commands;
    * access external systems or networks.
    """
    sentinel_input = {repr(sentinel)}

    with patch("{mock_target}") as mock_exec:
        mock_exec.return_value = MagicMock(returncode=0)
        try:
            {function_name}(sentinel_input)
        except Exception:
            # The function may raise due to mocked return value; that is
            # acceptable — we care only about how the mock was called.
            pass

        # --- Security assertions ---
{textwrap.indent(arg_assertion, "    ")}
'''
    return code


# ---------------------------------------------------------------------------
# Test-file path derivation
# ---------------------------------------------------------------------------


def _derive_test_file_path(target_file: str, function_name: str) -> str:
    """
    Derive an appropriate test file path inside the repository's tests directory.

    Keeps paths within the repository.  No path traversal is possible because
    the output is always tests/security/<stem>_<function>_security_test.py.
    """
    # Extract the stem of the target file (no directory, no extension).
    stem = Path(target_file).stem
    return f"tests/security/test_{stem}_{function_name}_security.py"


def _safe_test_file_path(test_file: str, repo_root: Path) -> Path:
    """
    Resolve *test_file* inside *repo_root* and verify path containment.

    Raises GenerationError on path traversal.
    """
    candidate = (repo_root / test_file).resolve()
    try:
        candidate.relative_to(repo_root.resolve())
    except ValueError:
        raise GenerationError(
            f"Derived test file path '{test_file}' resolves outside the "
            f"repository root.  Generation rejected."
        )
    return candidate


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------


def generate_security_test(
    finding: SecurityFinding,
    plan: RemediationPlan,
    patch: AppliedPatch,
    inventory: RepoInventory,
) -> tuple[SecurityRegressionTest, DesiredOutcome]:
    """
    Generate a behavioral security regression test and desired outcome for a
    successfully applied command-injection remediation.

    Parameters
    ----------
    finding:
        The SecurityFinding that initiated the remediation chain.
    plan:
        The RemediationPlan derived from *finding*.
    patch:
        The AppliedPatch produced from *plan*.  Must have applied=True.
    inventory:
        The RepoInventory snapshot used during earlier analysis stages.

    Returns
    -------
    tuple[SecurityRegressionTest, DesiredOutcome]
        Both artifacts share the same finding_id for full chain traceability.

    Raises
    ------
    TraceabilityError
        When finding → plan → patch IDs are inconsistent or patch.applied
        is False.
    GenerationError
        When a safe behavioral test cannot be constructed (unsupported
        vulnerability type, missing source evidence, etc.).
    """
    # ------------------------------------------------------------------
    # 1. Validate traceability chain
    # ------------------------------------------------------------------
    _validate_chain(finding, plan, patch)

    # ------------------------------------------------------------------
    # 2. Guard: only command_injection is supported in this vertical slice
    # ------------------------------------------------------------------
    if finding.vulnerability_type not in _SUPPORTED_VULNERABILITY_TYPES:
        raise GenerationError(
            f"Vulnerability type '{finding.vulnerability_type}' is not "
            f"supported by the v0 test generator.  "
            f"Only {sorted(_SUPPORTED_VULNERABILITY_TYPES)} are handled."
        )

    # ------------------------------------------------------------------
    # 3. Retrieve source evidence from inventory
    # ------------------------------------------------------------------
    source = _get_source(inventory, finding.file)
    if source is None:
        raise GenerationError(
            f"Source content for '{finding.file}' is not available in the "
            f"inventory (file may be binary, oversized, or missing).  "
            f"Cannot construct a behavioral test without source evidence."
        )

    # ------------------------------------------------------------------
    # 4. Infer function name and module path
    # ------------------------------------------------------------------
    function_name = _infer_function_name(source, finding.line)
    if function_name is None:
        raise GenerationError(
            f"Cannot determine the function enclosing line {finding.line} "
            f"in '{finding.file}'.  "
            f"A top-level expression or parse error prevents test generation."
        )

    module_path = _infer_module_path(finding.file)

    # ------------------------------------------------------------------
    # 5. Build the test function name and file path
    # ------------------------------------------------------------------
    test_name = f"test_{function_name}_rejects_shell_metacharacters"
    test_file = _derive_test_file_path(finding.file, function_name)

    # ------------------------------------------------------------------
    # 6. Build behavioral test code
    # ------------------------------------------------------------------
    test_code = _build_subprocess_list_test(
        module_path=module_path,
        function_name=function_name,
        test_name=test_name,
        sentinel=_SENTINEL_INPUT,
        sink=finding.sink,
    )

    # ------------------------------------------------------------------
    # 7. Assemble SecurityRegressionTest
    # ------------------------------------------------------------------
    regression_test = SecurityRegressionTest(
        test_id=_test_id(patch.patch_id),
        finding_id=finding.id,
        plan_id=plan.plan_id,
        patch_id=patch.patch_id,
        target_file=finding.file,
        test_file=test_file,
        test_name=test_name,
        security_property=(
            "Dynamic/untrusted values must remain data and must not be "
            "interpreted as shell syntax."
        ),
        test_code=test_code,
        expected_behavior=(
            f"Calling {function_name}() with the adversarial sentinel input "
            f"{repr(_SENTINEL_INPUT)} must result in the value being passed as "
            f"a discrete argument list element, not as part of a shell string.  "
            f"shell=True must be absent from the remediated call."
        ),
    )

    # ------------------------------------------------------------------
    # 8. Assemble DesiredOutcome
    # ------------------------------------------------------------------
    desired_outcome = DesiredOutcome(
        outcome_id=_outcome_id(finding.id),
        finding_id=finding.id,
        security_invariants=list(_SECURITY_INVARIANTS),
        regression_requirements=list(_REGRESSION_REQUIREMENTS),
        verification_requirements=list(_VERIFICATION_REQUIREMENTS),
    )

    logger.info(
        "Generated security regression test '%s' for finding '%s'.",
        regression_test.test_id,
        finding.id,
    )

    return regression_test, desired_outcome


def persist_security_test(
    test: SecurityRegressionTest,
    repo_path: str | os.PathLike,
) -> Path:
    """
    Write the generated test code to disk inside *repo_path*.

    Safety checks
    -------------
    * The destination path must resolve inside *repo_path* (no traversal).
    * The parent directory is created if it does not exist.
    * If a file already exists at the path and its content matches the
      generated test, the write is skipped (idempotent).
    * If a file exists with *different* content, writing is refused unless
      the existing file is also a generated security test (identified by
      the generated header comment).  This prevents silently overwriting
      unrelated tests.

    Parameters
    ----------
    test:
        A SecurityRegressionTest produced by generate_security_test().
    repo_path:
        Absolute (or resolvable) path to the controlled repository root.

    Returns
    -------
    Path
        The absolute path to the written test file.

    Raises
    ------
    GenerationError
        On path traversal, or if the target file already exists with
        unrelated content.
    OSError
        On write failures (propagated directly).
    """
    root = Path(repo_path).resolve()

    # Path containment
    target = _safe_test_file_path(test.test_file, root)

    # Create parent directories if needed.
    target.parent.mkdir(parents=True, exist_ok=True)

    # Idempotency and conflict detection.
    if target.exists():
        existing = target.read_text(encoding="utf-8")
        if existing == test.test_code:
            logger.debug("Test file '%s' already up to date; skipping write.", target)
            return target
        # Allow overwrite only if the existing file looks like a previously
        # generated security test (contains the generator header comment).
        if "Generated by secure_swe.test_generator." not in existing:
            raise GenerationError(
                f"File '{target}' already exists and does not appear to be a "
                f"previously generated security test.  Refusing to overwrite."
            )

    target.write_text(test.test_code, encoding="utf-8")
    logger.info("Wrote security regression test to '%s'.", target)
    return target
